### ISSUE TITLE
Menu Bar Titles are hard to read

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#62] opened 2016-04-18 00:12 UTC
lighten font of Menu Bar Titles to be legible on black menu bar.
Starts black, once you mouse over it become white and is more legible.

**Comment by virajmahesh** [comment] 2016-05-26 10:31
This is a duplicate of #171. But it should be fixed now.

**Closed** 2016-05-26 19:58 UTC
Labels: enhancement
