### ISSUE TITLE
[CRITICAL] User needs recourse when they lose their password.

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#149] opened 2016-05-16 17:46 UTC
Two possibilities:
1. Add "lost my password" button to Login screen.
Then i don't know what - whatever is easiest. Generate a temp password and email it to them? That email should also include a link back over to the Uprise LOGIN page so they can login with their temporary password?

**Comment by mplauche** [comment] 2016-05-17 15:34
Can we also prioritize this one? Because its going to happen. I'm open to work-around solutions and straight-up hacks, like putting my email up on the screen so they can contact me if they lost their password and then some sort of superuser powers to reset.

Or a temp password is generated and they go back to signup screen and somehow can still get back into their old account.

**Comment by virajmahesh** [comment] 2016-05-18 05:25
I think the standard way to handle this is to send an email with a link to a URL. Clicking on the URL allows you to set a new password. The advantage of doing it this way is that you can't reset someone else's password.

**Comment by virajmahesh** [comment] 2016-05-18 20:59
I was able to fully implement this. Waiting for you to approve #127 before I deploy this for you to test.

**Comment by mplauche** [comment] 2016-05-18 21:12
Hey - sorry, some more trouble on #127 cropped up. 
Can't wait to check out the password retrieval!

**Comment by virajmahesh** [comment] 2016-05-18 22:49
This should work now.

**Comment by mplauche** [comment] 2016-05-19 00:58
Very cool - interface is great. 

I got all the way to receiving my email with reset password instructions:

![capture d ecran 2016-05-18 a 5 56 05 pm](https://cloud.githubusercontent.com/assets/12802756/15379440/03058dac-1d22-11e6-9ece-560988641961.png)

Then when I clicked on the link, I got a safari error:
![capture d ecran 2016-05-18 a 5 55 51 pm](https://cloud.githubusercontent.com/assets/12802756/15379444/13c48530-1d22-11e6-82c5-14e6c4e24e0e.png)

**Comment by mplauche** [comment] 2016-05-19 01:10
But if I just replace that "localhost:3000/" with below, 

http://icsi-shift-scheduler-preview.herokuapp.com/users/password/edit?reset_password_token=FWxgJ3eGPsGqQQSyjWcD

It works! I see the final change password screen and can reset my password. 
I logged out and then back in with new password - all good!  I'm guessing you can fix that localhost thing pretty easily.

**Comment by virajmahesh** [comment] 2016-05-19 08:07
This should be fixed now. I also made another change that sends emails from @uprisecampaigns.org instead of @gmail.com,

**Comment by mplauche** [comment] 2016-05-19 17:39
I'm able to make it through the whole loop - I provide UserName (or Email), I click reset password button,  I get an email (from .org account), I follow the link, get back to UpRise to reset password, then I can log out and log back in with the new password. 

But I found a bug! If I attempt to log back in with the incorrect password, I get the following red screen:
![capture d ecran 2016-05-19 a 10 36 10 am](https://cloud.githubusercontent.com/assets/12802756/15403473/f4f57b5a-1dad-11e6-81eb-7794eeba6d60.png)

**Comment by virajmahesh** [comment] 2016-05-20 08:20
I wasn't able to reproduce this either.
Also, the delay in emails is due to switching to the new sender. This should speed up over time.

Can we mark this as closed, until the bug reappears?

**Closed** 2016-05-20 14:41 UTC
Labels: enhancement
