### ISSUE TITLE
User gets Notifications to FEED and EMAIL when one of their SKILLS is specified

### ISSUE THREAD

**Issue by mplauche** [virajmahesh/icsi-shift-scheduler#127] opened 2016-05-16 15:38 UTC
FEED text:

Your skill 'Cooking' is needed during the 'Canvassing' shift of the 'Caucus for Hillary' event.

EMAIL text:

Subject: Your skills are needed!

Someone needs your skills for the following shift. Can you help out?
April 10, 2018
Canvassing 10:00 AM - 10:40 AM
Skills Needed: Audio/Visual Tech/Microphones/Sound systems , Clean up/Set up/Extra pair of hands , Crowd control

Caucus for Hillary Berkeley, CA
April 10, 2018 10:00 AM - 11:00 AM
Event created by test_user(test_user@gmail.com)

**Comment by virajmahesh** [comment] 2016-05-17 01:01
What happens when multiple skills overlap? Is it okay to combine them into a single notification?

Also, where should clicking on the notification take you? To the event page or the shift page?

**Comment by mplauche** [comment] 2016-05-17 01:11
yes a single notification is okay. 
If the text is too long for FEED in the case of multiple skills, we could change it to:

Your skills are needed during the 'Canvassing' shift of the 'Caucus for Hillary' event.


Clicking on notification takes you to the shift page.

**Comment by virajmahesh** [comment] 2016-05-17 03:44
This is ready for testing

**Comment by mplauche** [comment] 2016-05-17 04:05
It worked when I (maddawg) created a shift that used my own skills. I got a notification in my feed. 

One small note - we need some punctuation on that notification: ' '   ' '  and .

But when richard signed up as rcarlson, he specified "programming" as a skill from down menu. 
When I created a shift that required programming, he wasn't notified by his FEED or EMAIL.

Also I noticed when he was signing up, he selected Driving/Delivery (which is kind of a long title) and when selected, it displayed as a long empty grey box with a few dots but no text.

**Comment by mplauche** [comment] 2016-05-17 04:12
ok no. Its working for Richard too. Email and Feed.
Here is the subtlety - 
if you CREATE a brand new SHIFT and specify someone's skills - they are notified  :)
If you EDIT an existing SHIFT, and specify someone's skills - nothing happens.

**Comment by virajmahesh** [comment] 2016-05-17 05:54
I think I've fixed the missing 's. 

Do you want EDIT shift to notify users about matches? It gets complicated very quickly to try and figure out who got notified about what, so as of now if editing the shift must notify users about matches, it's going to have to notify everyone who matches, ignoring all previous notifications.

**Comment by mplauche** [comment] 2016-05-17 15:24
Parentheses are there. Also a '.'  at the end of Notification, please. 

I think I want that - I think ignoring previous notifications is okay. Here are couple of weird scenarios I'm thinking about from a user perspective. Let me know if they are really complicated many hours of coding.

1. I signup for the first time and list 'programming' as my skill. Several events have shifts that specify that skill, so I immediately receive several corresponding notifications. (might be overwhelming, but i think it will get peeps engaged).

2. I am a nurse and when I signup for the first time, I list 'medical' as my only skill. An event is created for kid's rock climbing. The event has 1 shift for someone with 'childcare' as a skill and 10 shifts for participants. All users with 'childcare' as a skill are notified. Later on, the EC decides to EDIT the 1 shift for 'childcare' to require an additional skill: 'childcare' and 'medical'.   I, the nurse, now also get the notification.

Here is a scenario that would be a bummer (maybe this is what you mean):

An Event Creator specifies that they need the skill 'programming' and everyone gets  a notification, and then the EC EDITs the shift to change something else, like the time or to add a second skill, or improve their description. Then when they save their changes, everyone gets a notification for 'programming' again.

**Comment by virajmahesh** [comment] 2016-05-18 02:08
Added the .
Notifications are now generated even when shift is update, and a user is not notified twice about a matching shift. Let me know if this works as expected!

**Comment by mplauche** [comment] 2016-05-18 02:28
All this looks good - its much improved!

when i log out and log in, I don't get any new notifications (duplicate). :)
when i (as EC) edit a shift to include 'translation', i also get a notification (as a user with that skill). :)
when another user (EC) edits a shift to include 'translation', I get a notification(as a user with that skill). :)

This scenario doesn't work. Is this really hard to do? Or does it get complicated when trying to also capture logic above?
1. I signup for the first time and list 'programming' as my skill. Several events have shifts that specify that skill, so I immediately receive several corresponding notifications. (might be overwhelming, but i think it will get peeps engaged).

Can you take off the extra 's' on the end:
![capture d ecran 2016-05-17 a 7 26 07 pm](https://cloud.githubusercontent.com/assets/12802756/15345618/4cb14d32-1c65-11e6-8825-b7f00e8a0ad4.png)

**Comment by virajmahesh** [comment] 2016-05-18 03:31
Fixed the extra s, and you now get notifications when you sign up!

**Comment by mplauche** [comment] 2016-05-18 04:03
Hi! Haven't seen this screen in a while...I got it when I signed up as a test_user2 (with a bogus email). I gave a name, location, etc... and listed 3 skills. I think I skipped the issues (left them blank). Then clicked 'signup' and got this screen.
![capture d ecran 2016-05-17 a 9 01 27 pm](https://cloud.githubusercontent.com/assets/12802756/15347061/d6b745f6-1c72-11e6-933e-bdcf4bcb95ae.png)

**Comment by mplauche** [comment] 2016-05-18 04:06
then if i go back, i get this:
![capture d ecran 2016-05-17 a 9 06 11 pm](https://cloud.githubusercontent.com/assets/12802756/15347103/3a79b5f6-1c73-11e6-9b99-5174279c9c57.png)

**Comment by virajmahesh** [comment] 2016-05-18 05:19
The issue is happening due to orphaned shifts (i.e shifts without a parent event, because the parent event was deleted).
When I deleted the test events, the shifts for those events got left behind in the database. Now, when you created a new user, their skills matched with these orphaned shifts and the app errored trying to print the event information (because it doesn't exist!). But the signup was still successful, which is why hitting the back button said that the username and email were already in use.

The solution to this is:
1. We'll need to go in a delete shifts that don't have events. After that, you will be able to test the app without any issues.
2. We need to ensure that deleting an event triggers the deletion of the associated shifts too. It would be best if we have a separate issue to track this, as it is unrelated to the current issue.

**Comment by virajmahesh** [comment] 2016-05-18 10:25
#1 should be fixed now. If you create a new user with the same skills, it should not error.

**Comment by mplauche** [comment] 2016-05-18 21:00
I created a new user and specified some skills. 
I did not get an error :)

But I also did not get any notifications about existing shifts that needed my skills. :(

**Comment by virajmahesh** [comment] 2016-05-18 21:13
It seems like I accidently lost the changes that I made earlier. Will try and undo this and push again in ~15 minutes.

**Comment by virajmahesh** [comment] 2016-05-18 21:27
This should work now. I accidently deployed an older version of the code.

**Comment by mplauche** [comment] 2016-05-18 21:31
ok just a sec

**Comment by mplauche** [comment] 2016-05-18 21:37
Latest round of tests reveal:

I created a new user and specified some skills. I did not get the big red page error :)
When I signed up as a new user (and specified my skills) I did get LOTS of notifications about existing shifts that needed my skills. :)
When I CREATED a shift as an EC, I did get a notification (as a user) :)

When I EDITED a shift as an EC and added skills, I did NOT get a notification (as a user) that a shift needed my skills :(

**Comment by mplauche** [comment] 2016-05-18 21:42
Actually, I'm not so sure about that last problem. The email notification IS working - just a sec.... l

**Comment by virajmahesh** [comment] 2016-05-18 21:44
I just got a few email notifications about shifts. Forwarding them to you.

**Comment by mplauche** [comment] 2016-05-18 21:49
I don't know what was happening earlier. Now when I EDIT a shift and add a skill, user gets a notification that a shift needs their skills!

Email notifications are working, punctuation is good. All good.

It's only in a very weird case where there is some funny business. Here it is:

A user signs up with the following skills "programming" "Delivery/Driving"
Another EC creates a shift that needs "programming."
user gets a notification that their skills are needed. 
EC edits shift and deletes "programming". then comes back later and adds "programming". No notification. 
EC edits shift and deletes "programming" then comes back a week later and adds "Delivery/driving". No notification.

That's pretty weird cases. Let's call this issue closed and move on. GREAT WORK!

**Closed** 2016-05-18 21:53 UTC
Labels: enhancement
